name: Github pull request
run-name: Checking if everything works
on: 
    pull_request:
        branches: [master]
jobs:
    test_pull_req:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npm cypress run